### ISSUE TITLE
build-native.rb: JSON::ParserError  

### ISSUE THREAD

**Issue by nitanmarcel** [dantmnf/tdlib-netcore#1]
Hi! I'm unable to successfully run the `ruby build-native.rb` command as json fails to parse:

**Command used:** `ruby build-native.rb -- -DCMAKE_BUILD_TYPE=Release -DTD_ENABLE_LTO=ON`

**Console output:**

```
running ["cmake", "-DCMAKE_BUILD_TYPE=Release", "-DTD_ENABLE_LTO=ON", "--trace", "--trace-format=json-v1", "--trace-expand", "--trace-redirect=CMakeTrace.log", "-Wno-dev", "/home/nitanmarcel/RiderProjects/RgboardThemeGenTG/tdlib-netcore/td"]
Running with trace output on.
Running with trace output on.
Running with expanded trace output on.
Trace will be written to CMakeTrace.log
-- Use link time optimization CXX options: -flto -fno-fat-lto-objects
-- Use link time optimization C options: -flto -fno-fat-lto-objects
-- Use link time optimization linker options: 
-- Could NOT find ccache (this is NOT an error)
-- Found OpenSSL: /usr/include /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- Found ZLIB: /usr/include /usr/lib/x86_64-linux-gnu/libz.so
-- Could NOT find Readline (missing: READLINE_INCLUDE_DIR READLINE_LIBRARY) 
-- Could NOT find Readline (this is NOT an error)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nitanmarcel/RiderProjects/RgboardThemeGenTG/tdlib-netcore/build/tdjson
Traceback (most recent call last):
	9: from build-native.rb:61:in `<main>'
	8: from build-native.rb:61:in `chdir'
	7: from build-native.rb:132:in `block in <main>'
	6: from build-native.rb:132:in `chdir'
	5: from build-native.rb:135:in `block (2 levels) in <main>'
	4: from build-native.rb:68:in `block (2 levels) in <main>'
	3: from build-native.rb:68:in `map!'
	2: from build-native.rb:68:in `block (3 levels) in <main>'
	1: from /usr/lib/ruby/2.7.0/json/common.rb:156:in `parse'
/usr/lib/ruby/2.7.0/json/common.rb:156:in `parse': 783: unexpected token at 'home/nitanmarcel/RiderProjects/RgboardThemeGenTG/tdlib-netcore/td/CMakeLists.txt(1):  cmake_minimum_required(VERSION 3.0.2 FATAL_ERROR ) (JSON::ParserError)
```

**Comment by dantmnf** [comment]
Does `CMakeTrace.log` contains lines of JSON? This may require a recent version of CMake.

**Comment by nitanmarcel** [comment]
@dantmnf there's no lines of Json in `CMakeTrace.log` and about the cmake version I'm using is `3.16.3`

**Comment by dantmnf** [comment]
> the cmake versio I'm using is 3.16.3

`--trace-format=json-v1` is introduced in CMake 3.17

**Comment by nitanmarcel** [comment]
> > the cmake versio I'm using is 3.16.3
> 
> `--trace-format=json-v1` is introduced in CMake 3.17

Thanks for everything :)
